### ISSUE TITLE
Add version number to distribution

### ISSUE THREAD

**Issue by mvcatsifma** [jcassee/angular-hypermedia#12]

**Comment by jcassee** [comment]
The project gets its Bower distribution version number from Git tags. In what other way would you like to add a version number?

**Comment by mvcatsifma** [comment]
What I mean is that is would be handy to see the version number in the header of the distribution file, for instance while debugging in the browser. Just a minor improvement though ...

**Comment by jcassee** [comment]
That would be useful indeed. We could probably do that with a gulp text replacement plugin.

Found an example: http://www.miwurster.com/add-gits-revision-information-to-your-app-using-gulp/

**Comment by jcassee** [comment]
Fixed by #16
