### ISSUE TITLE
npm package?

### ISSUE THREAD

**Issue by stevermeister** [jcassee/angular-hypermedia#21]
could you please publish your package to npm?

**Comment by jcassee** [comment]
Sure! It would be my first package published to npm. Anything I would need to add to the project repository, or is it just registration?

**Comment by stevermeister** [comment]
yes, login and publish, should be easy 

https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by jcassee** [comment]
I published the latest version to npm. Does it work for you?

**Comment by stevermeister** [comment]
it's good also to specify dependencies that you have in bower also for npm

and probably remove 

```
   postinstall: "bower install"
```

if you want other people to use your package (not for development/contribution purposes )

**Comment by jcassee** [comment]
Version 0.7.4 has the changes I think are needed to use it as an npm module. More suggestions for improvement? (A PR would be ideal, of course.)

**Comment by stevermeister** [comment]
great, thank you!
