### ISSUE TITLE
typescript integration

### ISSUE THREAD

**Issue by geoHeil** [jcassee/angular-hypermedia#23]
How can I integrate your library into an angular typescript application? Where do I find the type definitions file?

**Comment by jcassee** [comment]
Good question! I do not use TypeScript myself. Do you have the time / inclination to provide the type definitions in a PR?

**Comment by geoHeil** [comment]
Unfortunately I will not have enough time ;(

**Comment by jcassee** [comment]
No problem. I will close this issue for now. If anyone want to do the work we can reopen it.
