### ISSUE TITLE
Generate info message if non-existent resource is requested

### ISSUE THREAD

**Issue by mvcatsifma** [jcassee/angular-hypermedia#4]
In the moment, if the client of the library requests a non-existent resource, the library ignores this request silently. Generate a info message instead, so that possible configuration errors are detected early.

context.loadPaths(resource, {doesnotexist: {}})

INFO: path 'doesnotexist'  does not exist

**Comment by mvcatsifma** [comment]
See pull request #7

**Comment by jcassee** [comment]
Fixed in 0.3.0 (4e4a311b58ff52f1394ab0032311844ddcd7b8f2).
